### ISSUE TITLE
Intellisense not working for CSHTML

### ISSUE THREAD

**Issue by sziencik** [LaubPlusCo/Helix-Templates#1]
All intellisense is being recognized asn ASPNETCORE.MVC instead of SYSTEM.WEB.MVC.  Do you have any examples with view intellisense working properly for SDK projects?

**Comment by anderslaub** [comment]
Hi,

Code-completion and other intellisense works in Visual Studio for the cshtml views. The errors that you are seeing is Visual Studio that attempts to compile the Razor views at design time using dotnetcore. You can safely "ignore" these errors by changing Output to only show Build rather than Build & Intellisense. The "Model" will still  have a red line but all code completion etc. work as normal.

Unfortunately the issue is a "feature" (bug) in Visual Studio where it is assumed that all Razor Views in SDK style C# projects are dotnetcore and should be compiled design time. This is clearly a bug since the project manifest is not respected.

I am working on finding a sustainable fix so Visual Studio will use classic ASPNET MVC design time when stated in the project manifest and configuration.

As a sidenote; The forthcoming update to these example SDK style templates will not rely on Visual Studio build tools (WebPublish) anymore. 

Among other highlights this removed dependency enable development from Visual Studio Code where no false errors are reported. This shows that it really just is an issue with the VS IDE and not the msbuild setup. Similar to the many Intellisense issues that VS encountered back when ASPNET MVC 4 was released.  

--Anders

**Comment by anderslaub** [comment]
To resolve this you need to add the following ProjectCapability to the build.

```
  <ItemGroup>
    <ProjectCapability Include="SupportsSystemWeb" />
  </ItemGroup>
```

This should be set either directly in each relevant .csproj file or in a properties file loaded by the projects. 

In the current Helix templates SDK solution example there are several different locations where you can set this, f.ex. add it in the existing _Build/props/Website.References.props file or you could also create a new file named Website.ProjectCapabilities.props, use directory.build.props etc.

Adding this ProjectCapability is tested and works in the latest versions of Visual Studio 2019. It may not resolve the issue in previous VS versions. 

No more red squiggles and exceptions thrown by Intellisense when working in classic aspnet mvc razor views.

**Comment by jhanson-dev** [comment]
Thank you!
